title: rasp0wn
author: rasp0wn
email: rasp0wn.hacking@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  En Rasp0wn encontrarás diversos tutoriales para aprender sobre ciberseguridad y desarrollar tus propios proyectos con Raspberry Pi.
  
# social links
twitter_username: rasp0wn # DO NOT include the @ character, or else the build will fail!
github_username:  rasp0wn # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
#theme: jekyll-theme-cayman
